In [54]:
##1.Create a Tensorflow Constant
import tensorflow as tf
values=[1,2,3]
constant_tensor=tf.constant(values)
print(constant_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [55]:
##2.Perform Element-Wise Operation
import tensorflow as tf
a=tf.constant([2,4,6])
b=tf.constant([1,2,3])
result=tf.multiply(a,b)
print(result)

tf.Tensor([ 2  8 18], shape=(3,), dtype=int32)


In [56]:
##3.Reshape a Tensor
import tensorflow as tf
x=tf.constant([1,2,3,4,5,6])
result=tf.reshape(x,[2,3])
print(result)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [57]:
##4.Extract a Slice
import tensorflow as tf
x=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
result=(x[:,1])
print(result)

tf.Tensor([2 5 8], shape=(3,), dtype=int32)


In [58]:
##5.Variable Initialization
import tensorflow as tf
weights=tf.constant(tf.random.normal(shape=(3,3)))
print(weights)

tf.Tensor(
[[-0.44685858  1.9712694   0.06877188]
 [-0.45733747 -0.63026285 -1.4060383 ]
 [ 0.37570843  1.2736263  -0.83616406]], shape=(3, 3), dtype=float32)


In [59]:
##6.Math Operations
import tensorflow as tf
x=tf.constant([[25.0,121.0],[625.0,64.0]])
result=tf.sqrt(x)
print(result)

tf.Tensor(
[[ 5. 11.]
 [25.  8.]], shape=(2, 2), dtype=float32)
